name: Terraform GitOps

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/environments/staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials (Staging)
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Configure AWS Credentials (Production)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (Staging)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Terraform Apply (Production)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd ../production
          terraform init
          terraform apply -auto-approve